# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knox', '0004_authtoken_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenExtended',
            fields=[
                ('token_digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ex', serialize=False, to='knox.AuthToken')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=16)),
                ('udid', models.CharField(max_length=1024)),
                ('push_token', models.CharField(max_length=1024, null=True)),
                ('lang', models.CharField(max_length=12, null=True)),
            ],
            options={
                'db_table': 'tokens_extended',
            },
        ),
    ]
