# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenextended',
            name='refresh_digest',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tokenextended',
            name='refresh_salt',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenextended',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('kodeos', 'Kodeos')], max_length=16),
        ),
    ]
