# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_session', '0002_auto_20160920_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenextended',
            name='refresh_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokenextended',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('kodeos', 'Kodeos'), ('ios', 'iOS')], max_length=16),
        ),
        migrations.AlterField(
            model_name='tokenextended',
            name='refresh_digest',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tokenextended',
            name='refresh_salt',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
